version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=parking-meter_db
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgres/data
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge